start_vertex: Optional[T_vertex] = None,
*,
start_vertices: Optional[Iterable[T_vertex]] = None,
build_paths: bool = False,
calculation_limit: Optional[int] = None,
already_visited: Optional[VertexIdSet[T_vertex_id]] = None,
